# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'BusinessNews' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BusinessNews

  target 'BusinessNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BusinessNewsUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'AFNetworking'
pod 'MJRefresh'
end
